### ISSUE TITLE
skip-intro.lua modification.

### ISSUE THREAD

**Issue by AdventurerRussia** [diniamo/mpv-fullscreen#1]
I see that the script works well, but it happens that there are openings where there is silence in the middle, I think for this we could add a rule that the script could start looking for silence after 1:15 to 1:40 
Usually, this is how many openings go, this would reduce false positives in opening parts of the opening where silence is going on.
at least the first minute can be accurately skipped for scanning.
I'm sorry, I'm writing through a translator.

**Comment by diniamo** [comment]
I didn't write the script, open an issue here: <https://github.com/rui-ddc/skip-intro>
